com.is1.proyecto.models.User:default
com.is1.proyecto.models.Profesor:default
com.is1.proyecto.models.Materia:default
com.is1.proyecto.models.Alumno:default
com.is1.proyecto.models.Beca:default
com.is1.proyecto.models.Cargo:default
com.is1.proyecto.models.Rendimiento:default
com.is1.proyecto.models.Inscripcion:default
